name: SlimeWeaponry
version: '${project.version}'
main: me.linoxgh.weaponryenhanced.WeaponryEnhanced
api-version: 1.17
softdepend: [ Slimefun ]
authors: [ LinoxGH ]
description: Adds new and unique weapons and armors with special effects.
